FROM golang:1.19-alpine AS builder

WORKDIR /app
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o thelistbot ./cmd/theList.go

FROM scratch
COPY --from=builder /app/thelistbot /thelistbot
ENTRYPOINT ["/thelistbot"]
